name:                drmaa-hs
version:             0.1.0.0
github:              "deepflowinc-oss/drmaa-hs"
license:             BSD3
author:              "DeepFlow, Inc."
maintainer:          "DeepFlow, Inc."
copyright:           "2023 (c) DeepFlow, Inc."

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/deepflowinc-oss/drmaa-hs#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- vector
- aeson

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wunused-packages

include-dirs:
- include

library:
  source-dirs: src
  extra-libraries:
  - drmaa2
  dependencies:
  - barbies
  - containers
  - inline-c
  - deepseq
  - derive-storable
  - derive-storable-plugin
  - hashable
  - safe-exceptions
  - semigroups
  - template-haskell
  - text
  - time
  - transformers
  - unordered-containers
  - vector

executables:
  drmaa-hs-smoke:
    main:                Main.hs
    source-dirs:         app/smoke
    build-tools:
    - tasty-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - drmaa-hs
    - barbies
    - directory
    - optparse-applicative
    - filepath
    - text
    - time
    - yaml
    - rio

tests:
  drmaa-hs-test:
    main:                Spec.hs
    source-dirs:         tests/unit
    build-tools:
    - tasty-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - drmaa-hs
    - barbies
    - text
    - tasty
    - tasty-hunit
    - tasty-quickcheck
