name:                effectful-extras
version:             0.1.0.0
license:             AllRightsReserved
author:              "DeepFlow, Inc."
maintainer:          "DeepFlow, Inc."
copyright:           "(c) 2023, DeepFlow, Inc."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Some great library and/or tool made by DeepFlow, Inc.

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Werror=deriving-defaults
- -Wunused-packages

dependencies:
- base >= 4.7 && < 5
# 外部パッケージ
- effectful-core
- safe-exceptions

library:
  source-dirs: src

tests:
  effectful-extras-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - effectful-extras
